# Generated by Django 3.2.9 on 2021-12-27 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp_id', models.IntegerField(default=0)),
                ('project_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Project')),
                ('description', models.CharField(default='###', max_length=50, verbose_name='Project Description')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.IntegerField(default=1, verbose_name='Time Stamp')),
                ('description', models.CharField(default='###', max_length=50, verbose_name='Description')),
                ('period', models.IntegerField(default=1, verbose_name='Period')),
                ('comparator_time_stamp_ID', models.IntegerField(default=1, verbose_name='Comparator')),
                ('melt', models.CharField(default='###', max_length=50, verbose_name='MELT')),
                ('population_growth_rate', models.IntegerField(default=1, verbose_name='Population Growth Rate')),
                ('investment_ratio', models.IntegerField(default=1, verbose_name='Investment Ratio')),
                ('labour_supply_response', models.CharField(default='###', max_length=50, verbose_name='Labour Supply Response')),
                ('price_response_type', models.CharField(default='###', max_length=50, verbose_name='Price Response Type')),
                ('melt_response_type', models.CharField(max_length=50, null=True, verbose_name='MELT Response Type')),
                ('currency_symbol', models.CharField(default='$', max_length=2, verbose_name='Currency Symbol')),
                ('quantity_symbol', models.CharField(default='#', max_length=2, verbose_name='Quantity Symbol')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to=settings.AUTH_USER_MODEL)),
                ('project_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_stamp', to='economy.project')),
            ],
            options={
                'verbose_name': 'Time Stamp',
                'verbose_name_plural': 'Time Stamps',
                'ordering': ['project_FK__number', 'time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(default='Initial', max_length=50, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_stamp_FK', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='economy.timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='ControlSuperState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M-C (exchange)', 'M-C (exchange)'), ("C-P-C' (produce)", "C-P-C' (produce)"), ("C'-M' (distribute)", "C'-M' (distribute)"), ('###', '###')], default='###', max_length=20)),
                ('first_substate_name', models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('Allocate', 'Allocate'), ('Trade', 'Trade'), ('Produce', 'Produce'), ('Prices', 'Prices'), ('Reproduce', 'Reproduce'), ('Revenue', 'Revenue'), ('Accumulate', 'Accumulate'), ('###', '###')], default='###', max_length=20)),
                ('next_superstate_name', models.CharField(choices=[('M-C (exchange)', 'M-C (exchange)'), ("C-P-C' (produce)", "C-P-C' (produce)"), ("C'-M' (distribute)", "C'-M' (distribute)"), ('###', '###')], default='###', max_length=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlSubState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('Allocate', 'Allocate'), ('Trade', 'Trade'), ('Produce', 'Produce'), ('Prices', 'Prices'), ('Reproduce', 'Reproduce'), ('Revenue', 'Revenue'), ('Accumulate', 'Accumulate'), ('###', '###')], max_length=20)),
                ('super_state_name', models.CharField(choices=[('M-C (exchange)', 'M-C (exchange)'), ("C-P-C' (produce)", "C-P-C' (produce)"), ("C'-M' (distribute)", "C'-M' (distribute)"), ('###', '###')], default='###', max_length=20)),
                ('next_substate_name', models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('Allocate', 'Allocate'), ('Trade', 'Trade'), ('Produce', 'Produce'), ('Prices', 'Prices'), ('Reproduce', 'Reproduce'), ('Revenue', 'Revenue'), ('Accumulate', 'Accumulate'), ('###', '###')], default='###', max_length=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
