# Generated by Django 3.2.9 on 2022-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='display_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='investment_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='periods_per_year',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='population_growth_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='project_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
