# Generated by Django 3.2.9 on 2022-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='melt',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='total_price',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='total_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='profit',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='profit_rate',
            field=models.FloatField(default=-1),
        ),
    ]
