# Generated by Django 3.2.9 on 2021-12-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='###', max_length=25, verbose_name='Name')),
                ('origin', models.CharField(choices=[('Social', 'Social'), ('Industrial', 'Industrial'), ('Money', 'Money'), ('###', '###')], default='###', max_length=20)),
                ('usage', models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', '###')], default='###', max_length=25, verbose_name='Usage')),
                ('size', models.FloatField(default=0, verbose_name='Quantity')),
                ('total_value', models.FloatField(default=0, verbose_name='Total Price')),
                ('total_price', models.FloatField(default=0, verbose_name='Total Value')),
                ('unit_value', models.FloatField(default=1, verbose_name='Unit Value')),
                ('unit_price', models.FloatField(default=1, verbose_name='Unit Price')),
                ('turnover_time', models.FloatField(default=360, verbose_name='Turnover Time')),
                ('demand', models.FloatField(default=0, verbose_name='Demand')),
                ('supply', models.FloatField(default=0, verbose_name='Supply')),
                ('allocation_ratio', models.FloatField(default=1, verbose_name='Allocation Ratio')),
                ('display_order', models.IntegerField(default=1, null=True)),
                ('image_name', models.CharField(default='###', max_length=25)),
                ('tooltip', models.CharField(default='###', max_length=50)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to=settings.AUTH_USER_MODEL)),
                ('time_stamp_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='economy.timestamp')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['time_stamp_FK'],
            },
        ),
        migrations.CreateModel(
            name='StockOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='###', max_length=50)),
                ('stock_owner_type', models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', '###')], default='###', max_length=20)),
                ('commodity_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_stockowner_related', to='economy.commodity')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='economy_stockowner_related', to=settings.AUTH_USER_MODEL)),
                ('time_stamp_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_stockowner_related', to='economy.timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('stockowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.stockowner')),
                ('output_scale', models.IntegerField(default=1, verbose_name='Output')),
                ('output_growth_rate', models.IntegerField(default=1, verbose_name='Growth Rate')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
            bases=('economy.stockowner',),
        ),
        migrations.CreateModel(
            name='SocialClass',
            fields=[
                ('stockowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.stockowner')),
                ('population', models.IntegerField(default=1000, verbose_name='Population')),
                ('participation_ratio', models.FloatField(default=1, verbose_name='Participation Ratio')),
                ('consumption_ratio', models.FloatField(default=1, verbose_name='Consumption Ratio')),
                ('revenue', models.FloatField(default=0, verbose_name='Revenue')),
                ('assets', models.FloatField(default=0, verbose_name='Assets')),
            ],
            options={
                'verbose_name': 'Social Class',
                'verbose_name_plural': 'Social Classes',
            },
            bases=('economy.stockowner',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', '###')], default='###', max_length=50, verbose_name='Stock Type')),
                ('owner_type', models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', '###')], default='###', max_length=20)),
                ('size', models.FloatField(default=0, verbose_name='Size')),
                ('stock_owner_name', models.CharField(default='###', max_length=50, verbose_name='Owner Name')),
                ('value', models.FloatField(default=0, verbose_name='Value')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('demand', models.FloatField(default=0, verbose_name='Demand')),
                ('supply', models.FloatField(default=0, verbose_name='Supply')),
                ('commodity_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.commodity', verbose_name='Commodity')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='economy_stock_related', to=settings.AUTH_USER_MODEL)),
                ('stock_owner_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.stockowner')),
                ('time_stamp_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_stock_related', to='economy.timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStock',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.stock')),
                ('consumption_requirement', models.FloatField(default=0, verbose_name='Consumption Requirement')),
                ('social_class_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_stock', to='economy.socialclass', verbose_name='Social Class')),
            ],
            options={
                'verbose_name': 'Social Stock',
                'verbose_name_plural': 'Social Stocks',
            },
            bases=('economy.stock',),
        ),
        migrations.CreateModel(
            name='IndustryStock',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.stock')),
                ('production_requirement', models.FloatField(default=0, verbose_name='Production Requirement')),
                ('industry_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Industry Stock',
                'verbose_name_plural': 'Industry Stocks',
            },
            bases=('economy.stock',),
        ),
    ]
