# Generated by Django 3.2.9 on 2022-01-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image_name',
            field=models.CharField(default='Undefined', max_length=25),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(default='Undefined', max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='origin',
            field=models.CharField(choices=[('Social', 'Social'), ('Industrial', 'Industrial'), ('Money', 'Money'), ('Undefined', 'UNDEFINED')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='tooltip',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='usage',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('Undefined', 'UNDEFINED')], default='Undefined', max_length=25, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='log',
            name='stage',
            field=models.CharField(default='Undefined', max_length=25),
        ),
        migrations.AlterField(
            model_name='log',
            name='step',
            field=models.CharField(default='Undefined', max_length=25),
        ),
        migrations.AlterField(
            model_name='stock',
            name='owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('Undefined', 'UNDEFINED')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_owner_name',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='usage_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('Undefined', 'UNDEFINED')], default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockowner',
            name='name',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockowner',
            name='stock_owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('Undefined', 'UNDEFINED')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='labour_supply_response',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='melt',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='price_response_type',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='stage',
            field=models.CharField(default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='step',
            field=models.CharField(default='Undefined', max_length=50),
        ),
    ]
