# Generated by Django 3.2.9 on 2022-02-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_owner_name',
        ),
    ]
