# Generated by Django 3.2.9 on 2022-02-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_trace_real_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='investment_ratio',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='labour_supply_response',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='melt_response_type',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='population_growth_rate',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='price_response_type',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='quantity_symbol',
        ),
        migrations.CreateModel(
            name='Simulation_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_year', models.IntegerField(default=1)),
                ('population_growth_rate', models.IntegerField(default=1)),
                ('investment_ratio', models.IntegerField(default=1)),
                ('labour_supply_response', models.CharField(default='Undefined', max_length=50)),
                ('price_response_type', models.CharField(default='Undefined', max_length=50)),
                ('melt_response_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=2)),
                ('quantity_symbol', models.CharField(default='#', max_length=2)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
