# Generated by Django 3.2.9 on 2022-02-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_auto_20220217_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='display_level',
        ),
        migrations.AddField(
            model_name='simulation',
            name='trace_display_level',
            field=models.IntegerField(default=5),
        ),
    ]
