# Generated by Django 3.2.9 on 2022-02-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_alter_commodity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='price_response_type',
        ),
    ]
