# Generated by Django 3.2.9 on 2021-12-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_commodity_industry_industrystock_socialclass_socialstock_stock_stockowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='sub_state_FK',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='economy.controlsubstate'),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='super_state_FK',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='economy.controlsuperstate'),
        ),
    ]
