# Generated by Django 3.2.9 on 2022-02-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_auto_20220204_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='simulation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.simulation_parameter'),
        ),
    ]
