# Generated by Django 3.2.9 on 2022-02-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_remove_simulation_price_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='price_response_type',
            field=models.CharField(default='Undefined', max_length=50),
        ),
    ]
