# Generated by Django 3.2.9 on 2021-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_auto_20211227_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsubstate',
            name='substate_URL',
            field=models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('Allocate', 'Allocate'), ('Trade', 'Trade'), ('Produce', 'Produce'), ('Prices', 'Prices'), ('Reproduce', 'Reproduce'), ('Revenue', 'Revenue'), ('Accumulate', 'Accumulate'), ('###', '###')], default='###', max_length=50),
        ),
    ]
