# Generated by Django 3.2.9 on 2022-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_auto_20220121_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
