# Generated by Django 3.2.9 on 2021-12-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_controlsubstate_substate_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlsubstate',
            old_name='substate_URL',
            new_name='URL',
        ),
    ]
