# Generated by Django 3.2.9 on 2022-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_simulation_price_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='melt',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='simulation',
            name='profit_rate',
            field=models.FloatField(default=1),
        ),
    ]
