# Generated by Django 3.2.9 on 2022-01-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_alter_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='state',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='owner',
        ),
    ]
