# Generated by Django 3.2.9 on 2022-02-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_alter_timestamp_simulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['time_stamp']},
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='project_number',
        ),
        migrations.AddField(
            model_name='simulation_parameter',
            name='project_number',
            field=models.IntegerField(default=1),
        ),
    ]
