# Generated by Django 3.2.9 on 2022-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20220214_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='current_capital',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='simulation',
            name='initial_capital',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='simulation',
            name='profit',
            field=models.FloatField(default=1),
        ),
    ]
