# Generated by Django 3.2.9 on 2021-12-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_rename_substate_url_controlsubstate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='comparator_time_stamp_ID',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='comparator_time_stamp_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='economy.timestamp'),
        ),
    ]
