# Generated by Django 3.2.9 on 2022-01-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_state_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockowner',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='owner',
        ),
        migrations.AddField(
            model_name='commodity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
