# Generated by Django 3.2.9 on 2022-01-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_auto_20220122_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_time_stamp_FK',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_time_stamp', to='economy.timestamp'),
        ),
    ]
