# Generated by Django 3.2.9 on 2022-02-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_auto_20220214_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='comparator_time_stamp',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparator_time_stamp', to='economy.timestamp'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='current_time_stamp',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_time_stamp', to='economy.timestamp'),
        ),
    ]
