# Generated by Django 3.2.9 on 2021-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_auto_20211228_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsuperstate',
            name='URL',
            field=models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('Allocate', 'Allocate'), ('Trade', 'Trade'), ('Produce', 'Produce'), ('Prices', 'Prices'), ('Reproduce', 'Reproduce'), ('Revenue', 'Revenue'), ('Accumulate', 'Accumulate'), ('###', '###')], default='###', max_length=50),
        ),
    ]
