# Generated by Django 3.2.9 on 2022-02-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_auto_20220215_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='comparator_time_stamp_FK',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='melt',
        ),
    ]
