# Generated by Django 3.2.9 on 2022-02-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_rename_simulation_timestamp_simulation_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='simulation_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.simulation_parameter'),
        ),
    ]
