# Generated by Django 3.2.9 on 2021-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_controlsuperstate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsubstate',
            name='next_super_state_name',
            field=models.CharField(choices=[('M-C (exchange)', 'M-C (exchange)'), ("C-P-C' (produce)", "C-P-C' (produce)"), ("C'-M' (distribute)", "C'-M' (distribute)"), ('###', '###')], default='###', max_length=20),
        ),
    ]
