# Generated by Django 3.2.9 on 2022-01-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_user_current_time_stamp_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_time_stamp_FK',
            new_name='current_time_stamp',
        ),
    ]
