# Generated by Django 3.2.9 on 2021-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_controlsubstate_next_super_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='sub_state_name',
            field=models.CharField(default='Demand', max_length=50),
        ),
    ]
