# Generated by Django 3.2.9 on 2022-01-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_rename_current_time_stamp_fk_user_current_time_stamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
