# Generated by Django 3.2.9 on 2021-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0009_timestamp_sub_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsuperstate',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='sub_state_FK',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='super_state_FK',
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='sub_state_name',
            field=models.CharField(default='demand', max_length=50),
        ),
        migrations.DeleteModel(
            name='ControlSubState',
        ),
        migrations.DeleteModel(
            name='ControlSuperState',
        ),
    ]
