# Generated by Django 3.2.9 on 2022-01-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0009_delete_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='industrystock',
            name='industry_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.industry'),
        ),
        migrations.AlterField(
            model_name='industrystock',
            name='production_requirement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='socialstock',
            name='consumption_requirement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='socialstock',
            name='social_class_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_stock', to='economy.socialclass'),
        ),
    ]
