# Generated by Django 3.2.9 on 2021-12-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_auto_20211231_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='sub_state_name',
        ),
    ]
