# Generated by Django 3.2.9 on 2022-01-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_auto_20220125_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['project_number', 'time_stamp']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='project_FK',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='project_number',
            field=models.IntegerField(default=1),
        ),
    ]
