# Generated by Django 3.2.9 on 2022-02-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_alter_simulation_parameter_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simulation_Parameter',
            new_name='Simulation',
        ),
    ]
