# Generated by Django 3.2.9 on 2022-01-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_auto_20211231_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['project_FK__number', 'time_stamp']},
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='sub_state_name',
        ),
        migrations.AddField(
            model_name='commodity',
            name='investment_proportion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='monetarily_effective_demand',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='current_capital',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='initial_capital',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='profit_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='work_in_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='stage',
            field=models.CharField(default='###', max_length=25),
        ),
        migrations.AddField(
            model_name='log',
            name='step',
            field=models.CharField(default='###', max_length=25),
        ),
        migrations.AddField(
            model_name='stock',
            name='monetary_demand',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='stage',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='step',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='origin',
            field=models.CharField(choices=[('Social', 'Social'), ('Industrial', 'Industrial'), ('Money', 'Money'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='usage',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', 'UNDEFINED')], default='###', max_length=25, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='demand', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='time_stamp_FK',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='economy.timestamp'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='commodity_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.commodity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='demand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_owner_name',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supply',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='usage_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', 'UNDEFINED')], default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockowner',
            name='stock_owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='comparator_time_stamp_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='economy.timestamp'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=2),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='investment_ratio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='labour_supply_response',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='melt',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='melt_response_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='population_growth_rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='price_response_type',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='project_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_stamp', to='economy.project'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='quantity_symbol',
            field=models.CharField(default='#', max_length=2),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='time_stamp',
            field=models.IntegerField(default=1),
        ),
    ]
