# Generated by Django 3.2.9 on 2022-02-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0011_rename_simulation_parameter_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='current_time_stamp',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_stamp_simulation', to='economy.timestamp'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_simulation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_user', to='economy.simulation'),
        ),
    ]
