# Generated by Django 3.2.9 on 2021-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0012_industry_initial_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='work_in_progress',
            field=models.FloatField(default=0),
        ),
    ]
