# Generated by Django 3.2.9 on 2022-01-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0012_alter_user_current_time_stamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Trace',
        ),
    ]
