# Generated by Django 3.2.9 on 2022-01-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0013_industry_work_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='current_capital',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='profit_rate',
            field=models.FloatField(default=0),
        ),
    ]
