# Generated by Django 3.2.9 on 2022-01-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0014_auto_20220101_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='substate',
            field=models.CharField(default='###', max_length=25),
        ),
    ]
