# Generated by Django 3.2.9 on 2022-02-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0015_trace_time_stamp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='user',
        ),
    ]
