# Generated by Django 3.2.9 on 2022-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0015_log_substate'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='verbose',
            field=models.BooleanField(default=True),
        ),
    ]
