# Generated by Django 3.2.9 on 2022-01-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0016_log_verbose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='verbose',
        ),
    ]
