# Generated by Django 3.2.9 on 2022-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0017_remove_log_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='investment_proportion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='monetarily_effective_demand',
            field=models.FloatField(default=0),
        ),
    ]
