# Generated by Django 3.2.9 on 2022-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0018_auto_20220102_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['project_FK__number', 'time_stamp']},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=2),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='description',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='investment_ratio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='labour_supply_response',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='melt',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='melt_response_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='population_growth_rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='price_response_type',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='quantity_symbol',
            field=models.CharField(default='#', max_length=2),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='time_stamp',
            field=models.IntegerField(default=1),
        ),
    ]
