# Generated by Django 3.2.9 on 2022-02-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0018_commodity_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='current_time_stamp',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.timestamp'),
        ),
    ]
