# Generated by Django 3.2.9 on 2022-01-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0019_auto_20220110_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={},
        ),
        migrations.AddField(
            model_name='stock',
            name='monetary_demand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='commodity_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.commodity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='demand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_owner_name',
            field=models.CharField(default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supply',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='usage_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', '###')], default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
