# Generated by Django 3.2.9 on 2022-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0020_auto_20220113_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='description',
            new_name='substate',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='super_state',
            field=models.CharField(default='###', max_length=50),
        ),
    ]
