# Generated by Django 3.2.9 on 2022-02-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0021_alter_commodity_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockowner',
            name='simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.simulation'),
        ),
    ]
