# Generated by Django 3.2.9 on 2022-01-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0021_auto_20220113_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='substate',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='timestamp',
            old_name='substate',
            new_name='step',
        ),
    ]
