# Generated by Django 3.2.9 on 2022-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0023_rename_super_state_timestamp_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='stage',
            field=models.CharField(default='###', max_length=25),
        ),
    ]
