# Generated by Django 3.2.9 on 2022-01-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0024_auto_20220115_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='time_stamp_FK',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='economy.timestamp'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='comparator_time_stamp_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='economy.timestamp'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='project_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_stamp', to='economy.project'),
        ),
    ]
