# Generated by Django 3.2.9 on 2022-01-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0025_auto_20220120_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='origin',
            field=models.CharField(choices=[('Social', 'Social'), ('Industrial', 'Industrial'), ('Money', 'Money'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='usage',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', 'UNDEFINED')], default='###', max_length=25, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='demand', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='usage_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Consumption', 'Consumption'), ('Money', 'Money'), ('Sales', 'Sales'), ('###', 'UNDEFINED')], default='###', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockowner',
            name='stock_owner_type',
            field=models.CharField(choices=[('Industry', 'Industry'), ('Social Class', 'Social Class'), ('###', 'UNDEFINED')], default='###', max_length=20),
        ),
    ]
